version: "3.7"

services:
  app:
    build: .
    image: docker.mofid.dev/whisper-large-v3-finetune
    ports:
      - 8012:8888
    volumes:
      - ./data:/home/user/app
      - ./Cache/:/home/user/temp/torch
      - ./Cache/:/home/user/temp/.cache

    environment:
      - GIT_PYTHON_REFRESH=quiet
      - HUGGINGFACE_HUB_CACHE=/home/user/temp/.cache
      - TRANSFORMERS_CACHE=/home/user/temp/.cache
      - HF_HOME=/home/user/temp/.cache
      - TORCH_HOME=/home/user/temp/torch
      #- TRANSFORMERS_OFFLINE=1
    shm_size: '2gb'
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0","1","2","3","4","5"]
              capabilities: [gpu]
